In [1]:
import torch
from torch import nn

In [ ]:
x=torch.randn(100,3)
layer = nn.Linear(3,5)
print(layer(x).shape)
print(layer.weight)
print(layer.bias)

torch.Size([100, 5])
Parameter containing:
tensor([[-0.5596,  0.3081,  0.0737],
        [-0.1788,  0.2255,  0.2457],
        [-0.5035,  0.2118,  0.1896],
        [ 0.3637, -0.0096, -0.0156],
        [-0.2717, -0.4274,  0.3892]], requires_grad=True)
Parameter containing:
tensor([-0.4923,  0.1977,  0.3918, -0.5080, -0.2248], requires_grad=True)


In [ ]:
# nn.ReLU()
x=torch.randn(2,5)
print(x)
print('-----layer(x)-----')
layer = nn.ReLU()
print(layer(x))

tensor([[ 0.9894,  0.3616,  0.2081,  2.6080,  0.4893],
        [-1.0875,  1.9309, -0.1152,  0.8040,  0.9570]])
-----layer(x)-----
tensor([[0.9894, 0.3616, 0.2081, 2.6080, 0.4893],
        [0.0000, 1.9309, 0.0000, 0.8040, 0.9570]])


In [ ]:
x = torch.randn(3,7)
print(x)

print('\n----dropout(x)-----\n')

dropout = nn.Dropout(p=0.3) # p는 죽일 확률을 의미한다
print(dropout(x))

tensor([[ 0.6277, -0.6989, -0.9930, -2.6160, -0.4282,  0.4142, -1.1904],
        [-1.4061, -0.2077, -1.5232, -1.4223,  1.8068,  0.3890, -0.6593],
        [ 1.6498,  1.7529,  0.6519, -0.4966,  0.6198,  1.5601, -1.6832]])

----dropout(x)-----

tensor([[ 0.0000, -0.9985, -1.4186, -3.7372, -0.0000,  0.5917, -1.7006],
        [-2.0087, -0.2967, -2.1761, -0.0000,  2.5812,  0.5558, -0.9418],
        [ 2.3569,  0.0000,  0.9313, -0.7094,  0.8854,  2.2288, -2.4046]])


In [ ]:
class sample_model(nn.Module):
    def __init__(self):
        super().__init__()
        self.drop_layer=nn.Sequential(nn.Linear(5,7),
                                      nn.Dropout(p=0.3))

    def forward(self, x):
        x = self.drop_layer(x)
        return x

model=sample_model()
model.train() # train mode로 전환
x=torch.randn(3,5) # 그 담에 x=torch.randn(2,3,5)
print(model(x))

model.eval()
print(model(x)) # test mode

tensor([[-1.4930, -0.0000, -0.6301,  0.0000,  0.7079,  0.4036, -0.7338],
        [-0.9870,  0.7944, -0.8682,  0.3421,  0.0000,  0.2003, -1.0916],
        [ 0.2608,  1.8789, -0.0362, -0.0000, -0.3514,  0.0000, -1.3306]],
       grad_fn=<MulBackward0>)
tensor([[-1.0451, -0.1022, -0.4411,  1.0483,  0.4955,  0.2825, -0.5136],
        [-0.6909,  0.5561, -0.6077,  0.2395,  0.6528,  0.1402, -0.7641],
        [ 0.1825,  1.3152, -0.0253, -1.5710, -0.2460,  0.4715, -0.9314]],
       grad_fn=<AddmmBackward0>)


In [ ]:
layer = nn.Conv2d(in_channels=1, out_channels=2, kernel_size=3, stride=1, padding=1) # stride=1, padding=0 이 디폴트
layer(torch.randn(32,1,5,5)).shape
# nn.Linear(3,5) # 채채 # 얘는 채 또는 개채를 원함, 개 x 3
# nn.Conv2d(3,5) # 채채 # 얘는 채행열 또는 개채행열을 원함, 개 x 3 x 행 x 열

torch.Size([32, 2, 5, 5])

In [ ]:
layer = nn.Conv2d(3,5,3, stride=2, padding=1) # 3개의 채널을 가지는 3 * 3 - output으로 5개의 채널을 유지한다
print(layer(torch.randn(32,3,5,5)).shape)
print(layer.weight.shape) # 입력의 채널에 맞춰야 한다

torch.Size([32, 5, 3, 3])
torch.Size([5, 3, 3, 3])


In [ ]:
conv1 = nn.Conv2d(1,8,6,stride=2) # 8 1 6 6 필터만 생각해보면
x=torch.randn(32,1,28,28)
print(conv1(x).shape) # 32 8 12 12

conv2 = nn.Conv2d(8,16,3,padding=1) # conv1을 통과하고 난 결과를 넣으려고 한다. 당연히 시작은 8이 되어야 한다
print(conv2(conv1(x)).shape) # 필터는 16 8 3 3 (당연히 앞의 채널을 따라가는 것 - 필터의 경우에는)

Maxpool = nn.MaxPool2d(kernel_size=2, stride=(2,2)) # Max Pooling을 진행한다 - 2x2 커널을 구성한다
print(Maxpool(conv2(conv1(x))).shape)

torch.Size([32, 8, 12, 12])
torch.Size([32, 16, 12, 12])
torch.Size([32, 16, 6, 6])


In [ ]:
#maxpool은 더 간단하게 작성이 가능하다
maxpool = nn.MaxPool2d(2) # kernel_size=2, stride(2,2) 자동 설정해준다
x=torch.randn(1,1,8,8)
print(x)
print(maxpool(x))
print(maxpool(torch.randn(32,3,8,8)).shape)

tensor([[[[-1.5890, -0.8548,  0.7102, -0.3267, -0.1107,  0.0463,  0.3847,
            2.4415],
          [ 0.4319, -0.0053,  1.5453, -0.4268,  0.0976, -1.5030,  0.2338,
           -0.0902],
          [-2.0332, -0.6003,  1.6654,  1.0421,  0.0259,  0.9413, -2.2681,
           -1.9195],
          [-1.6302, -0.8125,  0.7262,  0.5459,  0.5516,  1.0731, -0.3249,
           -0.1475],
          [-2.1134,  1.5511, -0.0340, -0.3412,  0.3452,  1.7629,  0.6470,
           -0.8676],
          [ 0.4510,  0.5359, -1.2164,  0.0902,  0.6231,  1.1105, -1.1698,
           -1.2846],
          [-0.1865, -1.5399, -0.5547, -0.6247, -0.4540, -0.3767, -1.0900,
           -0.7880],
          [-0.5428,  0.4317,  0.5138,  0.7418, -0.5739,  0.2876, -0.7764,
           -1.4470]]]])
tensor([[[[ 0.4319,  1.5453,  0.0976,  2.4415],
          [-0.6003,  1.6654,  1.0731, -0.1475],
          [ 1.5511,  0.0902,  1.7629,  0.6470],
          [ 0.4317,  0.7418,  0.2876, -0.7764]]]])
torch.Size([32, 3, 4, 4])


In [ ]:
avgpool=nn.AvgPool2d(2)
x=torch.randn(1,1,6,6)
print(x)
print(avgpool(x))
print(avgpool(torch.randn(32,3,6,6)).shape)

tensor([[[[-0.4368, -2.9541,  0.2818, -0.8517,  2.3035, -0.4870],
          [-0.3032,  2.3875, -1.2209,  0.9352, -0.4782,  0.7649],
          [-0.1029,  0.6436, -2.2293, -0.0964,  0.2487,  0.0521],
          [-0.6610,  0.3468, -0.9191,  0.7501, -0.2328, -0.6528],
          [ 0.4439, -1.1364,  1.4011,  1.8005,  1.7893, -0.0464],
          [ 0.4676,  0.9680, -0.0163, -1.1986,  0.7401, -0.1713]]]])
tensor([[[[-0.3267, -0.2139,  0.5258],
          [ 0.0566, -0.6237, -0.1462],
          [ 0.1858,  0.4967,  0.5779]]]])
torch.Size([32, 3, 3, 3])


In [ ]:
class CNN(nn.Module):
    def __init__(self):
        super().__init__()

        self.conv1 = nn.Conv2d(1,8,6,stride=2)
        self.conv2 = nn.Conv2d(8,16,3,padding=1)
        self.Maxpool2 = nn.MaxPool2d(2)
        self.fc = nn.Linear(16*6*6,10) # 최종의 경우에는 input_layer 계산하기 힘들다 따라서 forward()를 활용하자

    def forward(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.Maxpool2(x)
        # x = torch.flatten(x, start_dim = 1) # 개 채 형태를 원하는 nn.Linear() 조건을 만족시키기 위함
        # x = self.fc(x)
        return x

x = torch.randn(32, 1, 28, 28)
model = CNN()
print(model(x).shape)

torch.Size([32, 16, 6, 6])


## parameters() vs .modules() vs .children() 그리고 isinstance의 활용


In [2]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Sequential(nn.Linear(2,3),
                                 nn.ReLU())
        self.fc2 = nn.Sequential(nn.Linear(3,4),
                                 nn.ReLU())
        self.fc_out = nn.Sequential(nn.Linear(4,1),
                                    nn.Sigmoid())
    def forward(self,x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.fc_out(x)
        return x

model = MLP()
print(model(torch.randn(2,2)).shape)
print(model)

torch.Size([2, 1])
MLP(
  (fc1): Sequential(
    (0): Linear(in_features=2, out_features=3, bias=True)
    (1): ReLU()
  )
  (fc2): Sequential(
    (0): Linear(in_features=3, out_features=4, bias=True)
    (1): ReLU()
  )
  (fc_out): Sequential(
    (0): Linear(in_features=4, out_features=1, bias=True)
    (1): Sigmoid()
  )
)


In [3]:
model.parameters()

<generator object Module.parameters at 0x7d8ef4859150>

In [4]:
list(model.parameters())
# [layer0 weight 값, layer0 bias 값, layer1 weight 값, layer1 bias 값, ...]

[Parameter containing:
 tensor([[ 0.5718, -0.5565],
         [ 0.4243,  0.5868],
         [ 0.0136,  0.4668]], requires_grad=True),
 Parameter containing:
 tensor([-0.4221, -0.1459, -0.3303], requires_grad=True),
 Parameter containing:
 tensor([[ 0.4086,  0.3343, -0.2366],
         [-0.4822,  0.0380, -0.5531],
         [-0.3655, -0.1358,  0.4386],
         [-0.0645, -0.3017,  0.5303]], requires_grad=True),
 Parameter containing:
 tensor([0.3121, 0.5404, 0.0163, 0.2516], requires_grad=True),
 Parameter containing:
 tensor([[-0.1376,  0.1133, -0.2754,  0.1610]], requires_grad=True),
 Parameter containing:
 tensor([0.3428], requires_grad=True)]

In [8]:
# for tranfer learning
model=MLP()
print([p for p in model.parameters() if p.requires_grad])

for p in model.parameters(): # 전체 freeze
    p.requires_grad=False
model.fc_out = nn.Linear(4,10)
print('----Freeze----')
print([p for p in model.parameters() if p.requires_grad])
# params = [p for p in model.parameters() if p.requires_grad]
# print(params)

# from torch import optim
# optimizer = optim.Adam(params, lr=0.1)

[Parameter containing:
tensor([[-0.2687, -0.0484],
        [-0.2731, -0.4583],
        [-0.2263,  0.3680]], requires_grad=True), Parameter containing:
tensor([-0.5723, -0.6241,  0.5178], requires_grad=True), Parameter containing:
tensor([[-0.0916,  0.5280,  0.5182],
        [ 0.4819,  0.2751,  0.1031],
        [ 0.2741,  0.0537, -0.1994],
        [-0.2653,  0.1681, -0.3132]], requires_grad=True), Parameter containing:
tensor([0.5006, 0.0904, 0.2491, 0.4204], requires_grad=True), Parameter containing:
tensor([[-0.2132,  0.4244,  0.0428,  0.4850]], requires_grad=True), Parameter containing:
tensor([-0.2971], requires_grad=True)]
----Freeze----
[Parameter containing:
tensor([[-0.2335,  0.3593,  0.1969,  0.0024],
        [-0.1368,  0.4224, -0.0666,  0.2224],
        [ 0.0627, -0.4947,  0.3689, -0.3602],
        [-0.2246,  0.2528,  0.1898, -0.1496],
        [-0.4327,  0.0983,  0.0220, -0.4207],
        [-0.1348,  0.3451,  0.1419, -0.1108],
        [-0.0934,  0.3245,  0.4242, -0.2780],
     

In [ ]:
list(model.named_parameters())[0]
# [('layer0.weight', weight 값), ('layer0.bias', bias 값), ('layer1.weight', weight 값), ('layer1.bias', bias 값), ...]

('fc1.0.weight',
 Parameter containing:
 tensor([[-0.5452,  0.5751],
         [-0.0644, -0.6877],
         [ 0.6575, -0.1508]]))

In [ ]:
for name, p in model.named_parameters():
    print(name)
    print(p)

fc1.0.weight
Parameter containing:
tensor([[-0.5452,  0.5751],
        [-0.0644, -0.6877],
        [ 0.6575, -0.1508]])
fc1.0.bias
Parameter containing:
tensor([ 0.6272, -0.0664,  0.2360])
fc2.0.weight
Parameter containing:
tensor([[ 0.5599,  0.0688,  0.3299],
        [-0.0182,  0.3369, -0.2942],
        [ 0.2924, -0.1734, -0.2073],
        [-0.1864, -0.3772,  0.3823]])
fc2.0.bias
Parameter containing:
tensor([ 0.3054, -0.0807, -0.5657, -0.0237])
fc_out.weight
Parameter containing:
tensor([[-0.3471, -0.4160,  0.3337,  0.0543],
        [ 0.3257, -0.4261, -0.4191,  0.0860],
        [-0.2413, -0.3930,  0.4409, -0.4469],
        [-0.2699, -0.4423, -0.3768,  0.3711],
        [ 0.1516,  0.4115, -0.4174,  0.2343],
        [ 0.3090,  0.1035,  0.4266,  0.4121],
        [ 0.0990, -0.2585, -0.1924,  0.0846],
        [-0.3150,  0.2319, -0.2547,  0.0773],
        [ 0.1694, -0.2283, -0.3534,  0.0988],
        [ 0.0495, -0.4558,  0.3726,  0.2749]], requires_grad=True)
fc_out.bias
Parameter containing

In [ ]:
model.modules()

<generator object Module.modules at 0x7905fd1f18c0>

In [ ]:
list(model.modules())

[MLP(
   (fc1): Sequential(
     (0): Linear(in_features=2, out_features=3, bias=True)
     (1): ReLU()
   )
   (fc2): Sequential(
     (0): Linear(in_features=3, out_features=4, bias=True)
     (1): ReLU()
   )
   (fc_out): Linear(in_features=4, out_features=10, bias=True)
 ),
 Sequential(
   (0): Linear(in_features=2, out_features=3, bias=True)
   (1): ReLU()
 ),
 Linear(in_features=2, out_features=3, bias=True),
 ReLU(),
 Sequential(
   (0): Linear(in_features=3, out_features=4, bias=True)
   (1): ReLU()
 ),
 Linear(in_features=3, out_features=4, bias=True),
 ReLU(),
 Linear(in_features=4, out_features=10, bias=True)]

In [ ]:
print([m for m in model.modules() if isinstance(m,nn.Linear)])
print([m.weight for m in model.modules() if isinstance(m,nn.Linear)])
print([m.weight.grad for m in model.modules() if isinstance(m,nn.Linear)])

[Linear(in_features=2, out_features=3, bias=True), Linear(in_features=3, out_features=4, bias=True), Linear(in_features=4, out_features=10, bias=True)]
[Parameter containing:
tensor([[-0.5452,  0.5751],
        [-0.0644, -0.6877],
        [ 0.6575, -0.1508]]), Parameter containing:
tensor([[ 0.5599,  0.0688,  0.3299],
        [-0.0182,  0.3369, -0.2942],
        [ 0.2924, -0.1734, -0.2073],
        [-0.1864, -0.3772,  0.3823]]), Parameter containing:
tensor([[-0.3471, -0.4160,  0.3337,  0.0543],
        [ 0.3257, -0.4261, -0.4191,  0.0860],
        [-0.2413, -0.3930,  0.4409, -0.4469],
        [-0.2699, -0.4423, -0.3768,  0.3711],
        [ 0.1516,  0.4115, -0.4174,  0.2343],
        [ 0.3090,  0.1035,  0.4266,  0.4121],
        [ 0.0990, -0.2585, -0.1924,  0.0846],
        [-0.3150,  0.2319, -0.2547,  0.0773],
        [ 0.1694, -0.2283, -0.3534,  0.0988],
        [ 0.0495, -0.4558,  0.3726,  0.2749]], requires_grad=True)]
[None, None, None]


In [ ]:
# weight initialization에 활용
for m in model.modules():
    if isinstance(m, nn.Linear):
        nn.init.kaiming_normal_(m.weight)
        # nn.init.constant_(m.weight, 1)

print([m.weight for m in model.modules() if isinstance(m, nn.Linear)])

[Parameter containing:
tensor([[-1.5886,  1.2463],
        [-1.3048,  0.5952],
        [ 0.3485, -1.3259]]), Parameter containing:
tensor([[ 0.3543, -0.7509,  1.2967],
        [ 0.5697,  0.6614, -1.0192],
        [ 0.4188, -0.4358,  0.5584],
        [-0.3956,  0.6194,  1.0973]]), Parameter containing:
tensor([[-0.6101,  1.4406,  0.4689, -0.1864],
        [ 0.7790,  0.0492, -1.2095,  0.2841],
        [-0.2283,  0.9000,  0.2964, -0.1514],
        [ 0.8711, -0.4342, -1.2121, -1.2928],
        [ 0.4763, -0.3301,  0.3121,  0.4196],
        [ 0.7030,  1.7460, -0.4860, -0.1926],
        [ 0.1629, -0.6335, -0.4477,  0.8588],
        [ 0.7963,  0.7262, -1.4475,  0.3735],
        [ 1.5502, -0.1033,  1.5237, -0.1973],
        [ 0.0578, -0.0591, -0.3489, -0.1535]], requires_grad=True)]


In [ ]:
model.children()

<generator object Module.children at 0x7905fd1f2110>

In [ ]:
list(model.children())

[Sequential(
   (0): Linear(in_features=2, out_features=3, bias=True)
   (1): ReLU()
 ),
 Sequential(
   (0): Linear(in_features=3, out_features=4, bias=True)
   (1): ReLU()
 ),
 Linear(in_features=4, out_features=10, bias=True)]

In [ ]:
x = torch.randn(2,2)
list(model.children())[0](x)

tensor([[0.0000, 0.0000, 3.0430],
        [3.1006, 1.5673, 0.0000]])

In [ ]:
print(*list(model.children())[:2])
sub_network = nn.Sequential(*list(model.children())[:2])
print(sub_network)
print(sub_network(x))

Sequential(
  (0): Linear(in_features=2, out_features=3, bias=True)
  (1): ReLU()
) Sequential(
  (0): Linear(in_features=3, out_features=4, bias=True)
  (1): ReLU()
)
Sequential(
  (0): Sequential(
    (0): Linear(in_features=2, out_features=3, bias=True)
    (1): ReLU()
  )
  (1): Sequential(
    (0): Linear(in_features=3, out_features=4, bias=True)
    (1): ReLU()
  )
)
tensor([[4.2514, 0.0000, 1.1335, 3.3155],
        [0.2270, 2.7222, 0.0499, 0.0000]])


## ModuleList vs Sequential

In [9]:
fc=nn.Linear(3,3)
layer_list = [fc for _ in range(5)]
layers1 = nn.Sequential(*layer_list)
layers2 = nn.ModuleList(layer_list)
print(layers1)
print(layers2)

x=torch.randn(1,3)
print(layers1(x))

# # print(layers2(x)) # error!
for layer in layers2:
    x = layer(x)
print(x)

Sequential(
  (0): Linear(in_features=3, out_features=3, bias=True)
  (1): Linear(in_features=3, out_features=3, bias=True)
  (2): Linear(in_features=3, out_features=3, bias=True)
  (3): Linear(in_features=3, out_features=3, bias=True)
  (4): Linear(in_features=3, out_features=3, bias=True)
)
ModuleList(
  (0-4): 5 x Linear(in_features=3, out_features=3, bias=True)
)
tensor([[-0.0119,  0.5379,  0.3905]], grad_fn=<AddmmBackward0>)
tensor([[-0.0119,  0.5379,  0.3905]], grad_fn=<AddmmBackward0>)


In [ ]:
# 걍 리스트 쓰지 왜 nn.ModuleList 를 쓸까?
class testNet(nn.Module):
    def __init__(self):
        super().__init__()

        # self.Module_List = [nn.Linear(3,3), nn.Linear(3,3)] - parameters 등록되어있지 않기 때문에 동작이 불가능하다
        self.Module_List = nn.ModuleList([nn.Linear(3,3), nn.Linear(3,3)])

    def forward(self,x):
        for layer in self.Module_List:
            x = layer(x)
        return x

model=testNet()
print(model(torch.randn(1,3)))
print(model) # 그냥 리스트로 하면 등록이 안돼있다!

optimizer = optim.Adam(model.parameters(), lr = 0.1) # 등록이 안돼있으면 parameter를 못 찾는다!

NameError: name 'nn' is not defined

In [10]:
# 그럼 nn.Sequential 쓰고 말지 왜 굳이 nn.ModuleList?
class small_block(nn.Module):
    def __init__(self):
        super().__init__()
        self.block_x = nn.Linear(1,1)
        self.block_y = nn.Linear(1,1)

    def forward(self, x, y):
        x = self.block_x(x)
        y = self.block_y(y)
        return x, y

block = small_block()
print(block)
model = nn.Sequential(block, block)
print(model)

# model(torch.randn(1), torch.randn(1)) # error!
# nn.Sequential 이 가지고 있는 forward 함수를 call 하기 때문에 입력을 두 개 넣으면 안된다!!

# moduleList - forward 함수의 오버라이드를 진행한다고 생각하자 (입력을 두 개 넣어도 가능하다!)
model = nn.ModuleList([block,block])
x = torch.randn(1)
y = torch.randn(1)
for block in model:
    x, y = block(x,y)
print(x, y)

small_block(
  (block_x): Linear(in_features=1, out_features=1, bias=True)
  (block_y): Linear(in_features=1, out_features=1, bias=True)
)
Sequential(
  (0): small_block(
    (block_x): Linear(in_features=1, out_features=1, bias=True)
    (block_y): Linear(in_features=1, out_features=1, bias=True)
  )
  (1): small_block(
    (block_x): Linear(in_features=1, out_features=1, bias=True)
    (block_y): Linear(in_features=1, out_features=1, bias=True)
  )
)
tensor([0.2505], grad_fn=<ViewBackward0>) tensor([1.1723], grad_fn=<ViewBackward0>)
